import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import Services from '../components/Services'
import css from "../styles/Home.module.css"
import {client} from "../lib/client"
import { Pizza } from '../types/Pizza.type'
import Menu from '../components/Menu'

interface IProps {
  pizzas: Pizza[]
}

const Home: NextPage<IProps> = ({pizzas}) => {
  console.log(pizzas[0]._id)
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <Hero/>
          <Services/>
          <Menu pizzas={pizzas} />
        </main>

      </div>
    </Layout>
  )
}

export default Home

export const getServerSideProps : GetServerSideProps<IProps> = async () => {
  const query = '*[_type == "pizza"]'
  const pizzas = await client.fetch(query)
  return {
    props: {
      pizzas
    }
  }
}
